#!/bin/bash

# Ask for the administrator password upfront
sudo -v

# Retain sudo until finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Install Xcode cli tools
if ! eval 'xcode-select -p'; then
	echo 'Installing xcode command line tools'
    eval 'gcc'
else
	echo 'xcode command line tools are already installed'
fi

# Install and update Homebrew:
if ! eval 'brew -v'; then
    echo "Getting Homebrew..."
    sudo ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
    echo "Updating Homebrew..."
    brew update
    echo "Adding brew to path..."
    export PATH="/usr/local/bin:$PATH"
else
	echo 'homebrew is already installed'
fi

# Make Development directory
if ! eval 'cd ~/Development'; then
    echo "Making new directory: ~/Development"
    mkdir ~/Development
    cd ~/Development
else
	'Development directory exists'
fi

# Clone this repo
if ! eval 'cd Mac-Things'; then
    echo "Cloning Mac-Things github repo..."
    git clone https://github.com/forgreed/Mac-Things.git
    cd Mac-Things
else
	echo "Updating Mac-Things repo..."
	git pull
fi

# Remove any existing dotfiles
echo "Removing existing dotfiles..."
rm ~/.bash_profile
rm ~/.bashrc
rm ~/.bash_powerline
rm ~/.vimrc
rm ~/.tmux.conf
rm ~/.gitconfig
rm ~/.gitignore_global
rm -rf ~/Library/Application\ Support/Sublime\ Text\ 3
rm ~/.jshintrc
rm -rf ~/.vim

# bash
echo "Linking bash stuff..."
ln -s /Users/$USER/Development/Mac-Things/dotfiles/.bash_powerline ~/.bash_powerline
ln -s /Users/$USER/Development/Mac-Things/dotfiles/.bashrc ~/.bashrc
ln -s /Users/$USER/Development/Mac-Things/dotfiles/.bash_profile ~/.bash_profile

# vim
echo "Linking vim stuff..."
ln -s /Users/$USER/Development/Mac-Things/dotfiles/.vimrc ~/.vimrc
ln -s /Users/$USER/Development/Mac-Things/dotfiles/.vim/ ~/.vim

# git
echo "Linking git stuff..."
ln -s /Users/$USER/Development/Mac-Things/dotfiles/.gitconfig ~/.gitconfig
ln -s /Users/$USER/Development/Mac-Things/dotfiles/.gitignore_global ~/.gitignore_global
ln -s /Users/$USER/Development/Mac-Things/dotfiles/.git-completion ~/.git-completion

# tmux
echo "Linking tmux.conf..."
ln -s /Users/$USER/Development/Mac-Things/dotfiles/.tmux.conf ~/.tmux.conf

# sublime
echo "Linking sublime..."
ln -s /Users/$USER/Development/Mac-Things/Sublime\ Text\ 3/ ~/Library/Application\ Support/

# jshintrc
echo "Linking jshint..."
ln -s /Users/$USER/Development/Mac-Things/dotfiles/.jshintrc ~/.jshintrc
